---
title: Causas de Muerte en Uruguay
slug: causas-de-muerte-en-uruguay
date: '2021-05-06'
lang: es
content_type: learn
access: private
tier: standard
tags: []
draft: true
---

Parsear un pdf para analizar los datos de las causas de muerte en Uruguay.

``` r
library(pdftools)
```

    Warning: package 'pdftools' was built under R version 4.0.2

    Using poppler version 0.73.0

``` r
text <- pdf_text("informe_preliminiar_de_mortalidad.pdf")
head(text)
```

    [1] "Vigilancia de la Mortalidad por todas las causas\r\n                      Enero a julio\r\n                       2015-2020\r\n                 Informe Preliminar\r\n           Dra. Ima León (Directora de Sistemas de Información de la Salud)\r\n              Dra. Adriana Misa (Directora de Dpto. de Estadísticas Vitales)\r\n                                     Dr. Oscar Gianneo (Asesor de DIGESA)\r\n            Dirección General de la Salud\r\n             Ministerio de Salud Pública\r\n                     Setiembre 2020\r\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    [2] "Contenido\r\nConsideraciones ............................................................................................................................ 2\r\nMortalidad general enero a julio de 2015 a 2020 ......................................................................... 3\r\nCorredor Endémico ......................................................................................................................... 6\r\nVigilancia de mortalidad por enfermedades del sistema Circulatorio ....................................... 10\r\nVigilancia de la mortalidad por causas externas ....................................................................... 13\r\nVigilancia de la mortalidad por tumores malignos .................................................................... 16\r\n                                                                                                                                             1\r\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    [3] "Consideraciones\r\nEn el marco de la actual pandemia COVID 19, investigaciones internacionales y opiniones de\r\nexpertos plantean la importancia de realizar la vigilancia de causas de muerte que podrían verse\r\nincrementadas durante este año.\r\nLa vigilancia de la mortalidad por todas las causas y la comparación de las muertes observadas\r\ncon los valores esperados es una estrategia que tiene cada vez más aplicaciones en todo el\r\nmundo. El exceso de mortalidad se ha usado en el seguimiento de la repercusión de las\r\nepidemias de gripe, las olas de calor, otros eventos con impacto sobre la salud de la población y,\r\nen la actualidad, con la pandemia de COVID-19. La vigilancia del exceso de mortalidad por todas\r\nlas causas es una manera fiable y exhaustiva de medir el impacto general de la mortalidad por\r\nCOVID- 19, permite a las autoridades nacionales evaluar mejor la carga de la COVID-19 sin\r\ndepender de manera exclusiva de las pruebas moleculares1.\r\nEl exceso de mortalidad se define como el número notificado de muertes menos el número\r\nesperado de muertes durante este período. El número esperado se define a partir de las\r\ntendencias anteriores de la mortalidad. Las muertes en exceso no están definidas por el número\r\nde muertes cuya causa es la COVID-19, dado que otros factores pueden contribuir al exceso de\r\nmortalidad1.\r\nPara contribuir al conocimiento de la situación actual de la mortalidad de nuestro país, se\r\nrealizó el presente informe con datos 2020 preliminares. Es decir que provienen de bases que\r\nno han pasado por el correcto tratamiento de depuración y corrección2, que se realiza en forma\r\nanual, al cerrar el año estadístico correspondiente, por lo que las cifras oficiales (que se\r\npublicarán en 2021) seguramente variarán.\r\n1 OPS. Mejorar la vigilancia de la mortalidad por COVID-19 en América Latina y el Caribe mediante la\r\nvigilancia de la mortalidad por todas las causas Documento de orientación. Mayo del 2020\r\n2 Las bases preliminares contienen errores debidos a certificados duplicados, iniciados incompletos,\r\nfaltantes (certificados papel procedentes del interior que llegan por correo al Dpto. de Estadísticas Vitales\r\ncon uno a tres meses de atraso), y con omisiones de información. Técnicamente se recomienda\r\nprecaución en el uso y conclusiones que se realicen, de bases preliminares.\r\n                                                                                                             2\r\n"
    [4] "Mortalidad general enero a julio de 2015 a 2020\r\nConsiderando el número total de muertes del período enero a julio 2015 a 2020, continúa la\r\ntendencia al descenso. Lo mismo se observa desagregando por grandes grupos de edad (tabla 1,\r\ngráfico 1).\r\n     Tabla 1: Distribución del Nº de muertes según grupo de edad. Enero a Julio,\r\n                                         2015 a 2020. Total país.\r\n              Años        Total       < 60 años     60 y más     65 y más   Sin dato\r\n              2020        18500         3175         15310        14270        15\r\n              2019        19894         3390         16494        15438        10\r\n              2018        19080         3395         15655        14653        30\r\n              2017        19511         3291         16203        15220        17\r\n              2016        20286         3475         16538        15429       273\r\n              2015        19120         3377         15396        14437       347\r\nGráfico 1: Evolución de la mortalidad según grupo de edad. Enero a Julio 2015-2020. Total\r\npaís.\r\n          22.000\r\n          20.000\r\n          18.000\r\n          16.000\r\n          14.000\r\n          12.000\r\n          10.000\r\n            8.000\r\n            6.000\r\n            4.000\r\n            2.000\r\n                0\r\n                 2015        2016          2017         2018         2019       2020\r\n                                  Total       < 60 años      65 y más\r\n                                                                                           3\r\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    [5] "Con respecto a la mortalidad proporcional y tomando las cinco principales causas de muerte,\r\nlas enfermedades del aparato circulatorio y los tumores siguen siendo la primera y la segunda\r\ncausa de muerte 2020. Destacamos igualmente que en tercer lugar encontramos a las causas de\r\nmuerte mal definidas3, que no contribuyen al conocimiento de las causas prevalentes desde el\r\npunto de vista estadístico, ni de la planificación en salud (tabla 2, gráfico 2),\r\nTabla 2. Mortalidad proporcional para las principales Causas (en %) Enero a julio, 2015-2020\r\n   Principales causas                                          2015          2016        2017        2018        2019        2020\r\n   Tumores [neoplasias]                                         24,4         24,1        24,9         25,4        25,3        25,6\r\n   Enfermedades del sistema circulatorio                        27,9         27,3        26,1         25,2        25,0        25,4\r\n   Síntomas, signos y hallazgos anormales\r\n   clínicos y de laboratorio, no clasificados                   8,4           8,6         8,2         9,0         10,0        10,4\r\n   en otra parte\r\n   Enfermedades del sistema respiratorio                        10,0         11,2        10,0         8,8          9,5        8,9\r\n   Causas externas de morbilidad y de\r\n                                                                7,4           6,7         6,9         7,7          6,3        6,9\r\n   mortalidad\r\n   Resto de las causas                                          21,9         22,1        23,9         23,9        23,9        22,8\r\n   Total                                                       100,0        100,0       100,0        100,0       100,0       100,0\r\n3\r\n  Clasificación Internacional de Enfermedades de la Organización Mundial de la Salud (OMS), (CIE) 10ª revisión. ”- Capítulo XVIII de la\r\nCIE-10 de R00 a R99: “Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte\r\n                                                                                                                                      4\r\n"                                                                                                                                                                                                                                                                                                                                                      
    [6] "Gráfico 2. Mortalidad proporcional según 5 principales causas (en %) enero a julio, 2015-2020\r\n  30,0\r\n  25,0\r\n  20,0\r\n  15,0\r\n  10,0\r\n   5,0\r\n   0,0\r\n              2015           2016            2017              2018            2019             2020\r\n         Tumores [neoplasias]\r\n         Enfermedades del sistema circulatorio\r\n         Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte\r\n         Enfermedades del sistema respiratorio\r\n         Causas externas de morbilidad y de mortalidad\r\n                                                                                                         5\r\n"
